# Generated by Django 4.1 on 2022-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=40)),
                ('age', models.BooleanField()),
                ('dob', models.DateField()),
                ('contact', models.TextField(max_length=13)),
                ('s_contact', models.TextField(max_length=13)),
                ('country', models.TextField(max_length=10)),
                ('city', models.TextField(max_length=10)),
                ('reffral', models.TextField()),
                ('experienced', models.BooleanField()),
                ('work_status', models.BooleanField()),
                ('associated_clubs', models.TextField()),
                ('course', models.BooleanField()),
            ],
        ),
    ]
